### ISSUE TITLE
Submit button is missing

### ISSUE THREAD

**Issue by johanneskiesel** [webis-de/mturk-manager#49]
When I test my HIT in the sandbox, it does not show a submit button => I can not submit the HIT. The same Worker template works when I submit it in the official web interface.

For reference: webis19, project "Editorials Summarization"

**Comment by Kritten** [comment]
Hi, your template `test1` is invalid. Instead of `<body>` you wrote `<spanody>`.
I assume the template will work once you fix this.
Maybe I can include some simple html validation to prevent such errors.

Your template `test1.3` needs the surrounding html structure as stated in the documentation.
Its true that the original MTurk allows such templates, but the MTurk-API does not.
I could automatically add the html structure if missing, but that's currently a low priority.

Please close this issue if the above solves your problem.

**Comment by johanneskiesel** [comment]
Thanks Kristof! I can currently not test, but I trust your analysis. test1.3 is the only one that matters. In fact, I added the HTML body (with typo) and head for test1 by accident. Would have never thought there to be a difference between API and Web GUI! And the missing submit button (everything else working fine) is a strange effect for this problem.

Not sure if a HTML check is the right thing here.
